import type { Metadata } from "next";

import './globals.css'; // Or the correct path to your file
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {

  const session = await auth();


  return (
    <SessionProvider session={session}>
    <html>
      <body>
        {children}
        
      </body>
    </html>
    </SessionProvider>
  );
}
