"use client";

import { Poppins } from "next/font/google";

import { ColourfulText } from "@/components/ui/colorful-text";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { LoginButton } from "@/components/auth/login-button";
import { TypewriterEffect } from "@/components/ui/typewriter-effect";

const font = Poppins({
  subsets: ["latin"],
  weight: ["600"],
});

export default function Home() {
  const hackathonTitle = "Cougar hacks 2025"; // The title of our hackathon project
  const teamMembers = [
    " Aryan Jung Thapa",
    "Adarsha Bhagat ",
    " Rishikesh Bastakoti",
    " Siddhartha Bhattarai",
  ]; // The Team members related to our hackathon project
  const vision =
    "We are on a mission to deal with drugs. This is not just a hackathon for us. We are trying to empower people of this university by making an application that will help the people of this university to deal with drugs. We will achieve this in the best way possible. Our goal is simple give the poeple Quizzes, Connection with experts, AI Solutions, and the way they can report to the people of this university"; // What we are trying to achieve or the features that we have in this project
  const goals = [ // Simply what we are trying to achieve
    "Empower Peer to Peer Connections",
    "Offer AI-powered Q&A for immediate support",
    "Enable secure real-time communication via WebRTC(In this case we are using Webrtc for videoCall)",
    "Games related to Quizzes",
  ];
  const techStacks = [
    "Next JS",
    "Tailwind",
    "PrismaORM",
    "TypeScript",
    "Zod(For TypeScript Validation)",
    "ShadCnUI",
    "ActernityUI",
    "GROQ(For AI API)",
   
   
    
  ]

  return (
    <main
      className={cn(    // Cn is just a wrapper on top of clsx and TWMerge mainly imported from utils.
        "flex flex-col items-center justify-center min-h-screen bg-blue-100 p-8", // We are setting the flex to be a container then we are making it col-based and then aligning it to the center with the background being blue
        font.className  // This will help us to get the text generated by the class Poppins.
      )}
    >
      <div className={cn("text-center mb-8")}>  {/**Margin bottom to be 8 and text to be center */}
        <div className={cn("text-6xl font-bold")}>  {/**Text to be 6xl and font to be bold */}
          <ColourfulText text={hackathonTitle} />  {/** Here, we are just rendering the component. We are passing hackathonTitle, the value that is being passed to the prop  */}
          <br />
        </div>
      </div>

      <div className="flex flex-row flex-wrap justify-center gap-8 w-full max-w-4xl"> {/** Here, we are laying out two cards side by side */}
        {/* Idea Card  This is the idea card and we are using this so that we can */}
        <div className="bg-white rounded-xl shadow-md p-8 w-full md:w-1/2">
          <TypewriterEffect 
            words={[{ text: "I. D. E. A" }]}  
            className="text-black dark:text-white"                              
            cursorClassName="bg-black dark:bg-white"                                
          />

          <p className="text-gray-700 leading-relaxed mb-4">
            We are a team of 4 and our idea is to solve the mental health
            problem by connecting the students of Caldwell University with
            people or experts that have years of experience in solving mental
            health and drug-related diseases. With the help of this web app,
            you can connect with people around the world and you can also have
            the features of AI through which you can ask questions. Also, you
            will have the opportunity to call people for which we have used
            WebRTC, and our tech stacks are:
          </p>
          <h3 className="text-lg font-semibold text-blue-800 mb-2 ml-20">
            Tech Stacks
          </h3>
          <ul className="list-decimal list-inside text-gray-700 mb-4 items-center  ml-20">
              {techStacks.map((techStack, index) => (
                <li key={index}>{techStack}</li>
              ))}
            </ul>
          
        </div>

        {/* More About Us Card */}
        <div className="bg-white rounded-xl  p-8 w-full md:w-1/2"> {/**Media width to be 1/2 and border radius to be rounded or 0.75 on emphasize background-white  */}
          <h2 className="text-xl font-semibold text-green-800 mb-4">
            More About Us
          </h2>
          <div>
            <h3 className="text-lg font-semibold text-green-700 mb-2">
              Our Team
            </h3>
            <ul className="list-decimal list-inside text-gray-700 mb-4">
              {teamMembers.map((member, index) => (
                <li key={index}>{member}</li>
              ))}
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-green-700 mb-2">
              Our Vision
            </h3>
            <p className="text-gray-700 leading-relaxed mb-4">{vision}</p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-green-700 mb-2">
              What We Want to Achieve
            </h3>
            <ul className="list-disc list-inside text-gray-700">
              {goals.map((goal, index) => (
                <li key={index}>{goal}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>

     <LoginButton>
        <Button
          variant="secondary"
          size="lg"
          className="flex mx-auto mt-10 bg-stone-500 text-white"
        >
          Sign in / Signup
        </Button>
     </LoginButton>
      
    </main>
  );
}
